name: Test
on: [ push, pull_request ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t mediasnacks-test .

      - name: Run tests in Docker
        run: docker run --rm mediasnacks-test npm run test
